### ISSUE TITLE
Odd bake on highres chunk

### ISSUE THREAD

**Issue by QuantumEntangledAndy** [norman784/gaiku#16]
In my terrain I have some high res chunks. Sometimes when (voxel) baking these chunks it ends up looking very odd

<img width="1019" alt="Screenshot 2021-01-03 at 11 27 32" src="https://user-images.githubusercontent.com/13386481/103875032-7b94cb00-5104-11eb-85c0-468c32b446b5.png">
(Green highres, blue med res, red low res)

I think perhaps it is the indexes but I am not sure. Any ideas before I go down the debugging rabbit hole?

It is consistent and for the same seed it will make the same odd chunk

**Comment by norman784** [comment]
Can you create a gist with the minimal code to reproduce the issue?

**Comment by QuantumEntangledAndy** [comment]
My code is quite complex. Random noise, background loaders and all the amethyst overhead aswell. I can reduce it down but there are a lot of moving elements so it will take time.

**Comment by QuantumEntangledAndy** [comment]
So I think I have traced this down to this line

https://github.com/norman784/gaiku/blob/b766561e05520e47b2de4d181ef61b2baa1f7eec/gaiku-3d/src/bakers/voxel.rs#L219

The number of verts in my high resolution bake exceeds 65535 and the index rolls around back to zero.

I can replace it with:

```rust
index: next_index.try_into().expect("Too many verticies"),
```

So that it will give a nice message on why its not working and panic. Or we could increase the index size to usize

**Comment by norman784** [comment]
I need to refactor the code, once I get it working again, so we can reduce the casts, because it can cause issues like you.

**Comment by norman784** [comment]
Did you solve this issue in your game?

**Comment by QuantumEntangledAndy** [comment]
It should be I am just doing a full rebuild from master to be sure before I close those three issues. But that takes quite some time to compile.
