### ISSUE TITLE
Out of bounds

### ISSUE THREAD

**Issue by QuantumEntangledAndy** [norman784/gaiku#20]
Trying to use the latest master with stock `Chunk` but I am getting OutOfBounds when voxel baking the chunk with dimensions `[112, 146, 52]`.

```rust
thread '<unnamed>' panicked at 'Out of bounds MeshBuilderData { position: [5.0, 146.0, 13.0], normal: Some([0.0, 1.0, 0.0]), uv: Some([0.0625, 0.9375]), atlas_index: 1, index: 540 }
', /Users/awk21/Projects/Software/gaiku/gaiku-common/src/mesh.rs:368:36
```

I think this may be to do with the boundary check not including an epsilon error or the last value

```rust
pub fn contains(&self, point: &Vector3<f32>) -> bool {
    self.start.x < point.x
      && self.start.y < point.y
      && self.start.z < point.z
      && self.end.x > point.x
      && self.end.y > point.y
      && self.end.z > point.z
  }
```

Perhaps something like this?
```rust
pub fn contains(&self, point: &Vector3<f32>) -> bool {
    const EPSILON: f32 = 1e-7;
    self.start.x - EPSILON <= point.x
      && self.start.y - EPSILON <= point.y
      && self.start.z - EPSILON <= point.z
      && self.end.x +EPSILON >= point.x
      && self.end.y + EPSILON >= point.y
      && self.end.z + EPSILON >= point.z
  }
```

**Comment by QuantumEntangledAndy** [comment]
Since vertices are always integers perhaps it would be better to use u32/64 rather than f32 for internal calculations to avoid the rounding errors inherent in f32

**Comment by QuantumEntangledAndy** [comment]
Oh nevermind I see you have EPSILON at init

**Comment by QuantumEntangledAndy** [comment]
Going down the debugging hole.....

I added this:

```rust
pub fn contains(&self, point: &Vector3<f32>) -> bool {
    println!("Range {:?}--{:?}", self.start, self.end);
    self.start.x < point.x
```

To print out the limits and got this just before the panic:

```rust
Range Vector3 { x: -0.000001, y: -0.000001, z: -0.000001 }--Vector3 { x: 112.0, y: 146.0, z: 52.0 }
```

Reducing the espilon down to 1e-5 and it works. According to rust `f32::DIGITS` there are 6 sf of digits if we use 1e-6 (your original) it assumes very little round error. From my work before I usually find that the safest epsilon is half the number of significant digits representable by the type. For doubles (f64) this is about 6-7 for singles (f32) this is only about 3-4 digits.

**Comment by QuantumEntangledAndy** [comment]
Talking more about significant figures (sf):

F32 has 6 significant figures. 

- for the number 145.0 + 1e-6

```
Sigfig: 123 456789
__________________
        145.000
       +  0.000001
       ----------
        145.000
```

3 of those SF are used for the 145. You cannot add 1e-6 because 145.000001 is 9sf which cannot be represented in f32.

To do epsilon correctly we would need to do something different than just a fixed subtraction. This is why float comparison is done as

```
((a-b)/b).abs() < EPSILON
```

Which is looking at relative error.

**Comment by QuantumEntangledAndy** [comment]
For this to work I think we should use relative error when setting the limits by using this: 

```
v * (1.+/-EPSILON)
```

Rather than

```
v +/- EPSILON
```

**Comment by norman784** [comment]
Cool, I'm glad that you manage to fix the issue. If you have time to submit a PR with the fix, I'm gladly will merge it.

**Comment by norman784** [comment]
I think this issue is solved. Closing now.
