### ISSUE TITLE
Crate name inconsistency

### ISSUE THREAD

**Issue by QuantumEntangledAndy** [norman784/gaiku#40]
Some crates have their name seperated with `-` and others with `_`.

`gaiku-3d`

`gaiku_amethyst`

It would perhaps be clearer if this was all either `-` or `_` rather than a mixture across the project

**Comment by QuantumEntangledAndy** [comment]
Ah I see that `gaiku-3d` is now empty... No worries I am trying to get the braking changes resolved and missed that...

**Comment by norman784** [comment]
Yes, I really like the crates names with `-`, but for the sake of consistency (when adding to the dependency and importing in the project) I find `_` better, so that's why I'm renaming the crate.
