### ISSUE TITLE
Default color is transparent

### ISSUE THREAD

**Issue by QuantumEntangledAndy** [norman784/gaiku#9]
Althouth not exactly an issue it was unexpected. I was generating a random terrian using the `noise` crate, baking it in gaiku (with colors since I plan added random colors too) and rendering it in amethyst. For a long time I was not seeing anything and was surprised. Until I realized that the default color of the goxel is transparent

https://github.com/norman784/gaiku/blob/6153d90a06d5cacbd1c15021954b95e7411ef172/gaiku-common/src/data/chunk.rs#L26-L28

Would it be more intuitive to the user if this were white.

**Comment by norman784** [comment]
I did that way because I was allocating the memory for colors and the data, when you create a chunk it is empty, so makes sense to be transparent I think.

Maybe we can add another constructor that allows you to pass the default color:

```rust
Chunk impl {
  pub fn new(position: [f32; 3], width: usize, height: usize, depth: usize) -> Self {
      Self::with_color(position, width, height, usize, depth, [0, 0, 0, 0])
  }

  pub fn with_color(position: [f32; 3], width: usize, height: usize, depth: usize, color: [u8, u8, u8, u8]) -> Self {
    Chunk {
        colors: vec![color.into(); depth * height * width],
        position: position.into(),
        width,
        height,
        depth,
        values: vec![0; depth * height * width],
      }
  }
}
```

**Comment by QuantumEntangledAndy** [comment]
If you want it to be transparent when empty it would be reasonable to also think that after it has a goxel in it then that goxel would not be transparent. Maybe therefore it would make more sense to add in the color when `set` is called with a non zero value.

```rust
pub fn set(&mut self, x: usize, y: usize, z: usize, value: u8) {
      let index = self.index(x, y, z);
      self.values[index] = value;
      if value != 0 {
          self.set_color(x, y, z, self.default_color);
     }
  }
```

**Comment by norman784** [comment]
Makes sense, but I would prefer not to store extra data in the chunk struct if not necessary, so we can add an optional argument to set method.

Can you submit a PR with this change?

**Comment by QuantumEntangledAndy** [comment]
What about just white or black for the default rather than a parameter? They are both reasonable choices and would give the end user a more expected result than transparent. I am currently working up a PR which centers the origin to the center of the chunk, would you like this to be included together?

**Comment by norman784** [comment]
Let's set the white color for the current position only if the color is "empty" and the value > 0 else we clear the color to black/transparent.

**Comment by QuantumEntangledAndy** [comment]
How do you intent to make an optional parameter in rust? I was under the impression rust does not support parameters with default values

**Comment by QuantumEntangledAndy** [comment]
We can make a function with a differnt name instead

```rust
   pub fn set(&mut self, x: usize, y: usize, z: usize, value: u8) {
        if value != 0 {
            self.set_with_color(x, y, z, value, [0, 0, 0, 1].into());
        } else {
            self.set_with_color(x, y, z, value, [0, 0, 0, 0].into());
        }
    }

    pub fn set_with_color(&mut self, x: usize, y: usize, z: usize, value: u8, color: Vector4<u8>) {
        let index = self.index(x, y, z);
        self.values[index] = value;
        self.set_color(x, y, z, color);
    }
```

**Comment by norman784** [comment]
By optional I mean using `Option`.

```rust
pub fn set(&mut self, x: usize, y: usize, z: usize, value: u8, color: Option<Vector4<u8>>);
```

**Comment by QuantumEntangledAndy** [comment]
We would still have to pass a `None` explicitly though. What do you think about the seperate function under a different name method?

**Comment by norman784** [comment]
I like the `set_with_color`, it will be a replacement of `set_color` (we can remove the later), because my initial idea was to set the color of the block, but doing two calls to set the value and color doesn't make too much sense, and I doubt you will just swap the color without chaning the value too for an existing block.

I was thinking on adding `uv` support in the future, maybe this is the opportunity to add some more types too, I should refactor how the texture is handled:

```rust
enum Texture {
    Color(u8, u8, u8, u8),
    Index(u16),
    None,
    UV(f32, f32),
}

struct Chunk {
    position: Vector3<f32>,
    texture: Vec<Texture>,
    width: usize,
    height: usize,
    depth: usize,
    values: Vec<u8>,
}

impl Chunk {
    fn get(&mut self, x: usize, y: usize, z: usize) -> u8;
    fn get_with_texture(&mut self, x: usize, y: usize, z: usize) -> (u8, Texture);
    fn set(&mut self, x: usize, y: usize, z: usize, value: u8);
    fn set_with_texture(&mut self, x: usize, y: usize, z: usize, value: u8, texture: Texture);
}
```
Maybe this needs to be addressed in a separate PR. Let me know what do you think.

**Edit:** Also I can maybe make chunk a trait and let the user define their own chunk (but also provide a default implementation), because will be hard to fit all needs without add too much bloat to the chunks.

**Comment by QuantumEntangledAndy** [comment]
I currently convert colors to uvs and generate a texture in the amethyst example. I am not sure about Index, I suppose you could maybe map a material to an index but it would be on the users code to decide the specifics.

Amethyst verticies can have both vertex colors and uvs (but only seems to render uvs as far as I could tell)

**Comment by norman784** [comment]
We need to work around that and see if we can move some of the code to the common crate, because other engines can benefit from it too, this is some topic I need to think about it.

Yes the index is managed in the userland, I was thinking in minecraft like games that mange it that way, but maybe the enum will bloat the chunk size even more if we add too much use cases.

**Comment by QuantumEntangledAndy** [comment]
The code for uv and texture creation is already in the common crate in `gaiku-common/src/data/mesh.rs`. The only part in amethyst is the bits for the conversions from the common to amethyst structures.

**Comment by QuantumEntangledAndy** [comment]
I have a plan to make volumetric textures for materials. Something like procedurally generated stone and wood textures. For this to work I need to UV unwrap and blit into the triangles location on the texture. Maybe these sorts of methods would be appropiate for the common crate. Indexes would be welcome to keep track of what goxel uses which material but I think they add to rather than replace UVs.

**Comment by QuantumEntangledAndy** [comment]
The current implementation of uv and texture in the common crate, uses the same UV coordinates for all faces with the same color, but a volumetric texture would likely need unique cooridnates for all. This may be a userland thing

**Comment by norman784** [comment]
I was working on a PR with a lot of changes that might help with this kind of customizations, I will wait till #10 is ready and merged before uploading it.
